services:
  app:
    build: .
    container_name: images-hosting
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/logs
      - ./images:/images

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - app
    env_file:
      - .env
    command: >
      caddy reverse-proxy
      --from ${DOMAIN}
      --to app:8000
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
